source("libraries.R")
source("data_paths.R")
source("error_messages.R")
source("functions.R")
source("data_load.R")

minDate=as.Date(min(dfModern$Date,dfPioneer$Date,dfPauper$Date))
maxDate=as.Date(max(dfModern$Date,dfPioneer$Date,dfPauper$Date))

navbarPage("MTGO results analysis",
           theme = shinytheme("cerulean"),
           tabPanel("Presence",
                    sidebarPanel(
                      
                      selectInput(inputId = "presenceFormat", 
                                  label = h4("Format"),
                                  choices = c("Modern","Pioneer","Pauper")),
                      bsPopover(id = "presenceFormat", 
                                title = "Select the format of tournaments you want to cover.", 
                                content = "Currently only Modern and Pioneer are supported for archetype recognition",
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId="presenceDates1", 
                                label=h4("From"), 
                                value = as.Date(maxDate) - 27,
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "presenceDates1", 
                                title = "Beginning date",
                                content = "Select the first date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId="presenceDates2", 
                                label = h4("To"), 
                                value = maxDate + days(1),
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "presenceDates2", 
                                title = "End date",
                                content = "Select the last date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "presencePrelims", 
                                    label = h4("Preliminaries"), 
                                    value = TRUE),
                      bsPopover(id = "presencePrelims", 
                                title = "Preliminary data",
                                content = "Indicate whether you want to include or not Preliminary data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "presenceChallenges", 
                                    label = h4("Major Official Events"), 
                                    value = TRUE),
                      bsPopover(id = "presenceChallenges", 
                                title = "Major Event data",
                                content = "Indicate whether you want to include or not Challenge and bigger event data.", 
                                placement = "top", 
                                trigger = "hover"),

                      numericInput(inputId='presenceShare', 
                                   label = h4("Percent for \"Other\""),
                                   value = 2,
                                   min = 0.1,
                                   max = 10,
                                   step = 0.1),
                      bsPopover(id = "presenceShare", 
                                title = "Percentage to be added to \"Other\"",
                                content = "Select the percentage under which a deck is put in the \"Other\" category.",
                                placement = "top", 
                                trigger = "hover"),

                      selectInput(inputId = "presenceType", 
                                  label = h4("Type of Presence"),
                                  choices = c("Matches", "Copies", "Players")),
                      bsPopover(id = "presenceType", 
                                title = "Select the variable that is used to determine archetype presence.", 
                                content = "Matches - the overall number of matches of the archetype, played in Swiss rounds and top8 if applicable. Copies - the number of times the archetype appeared in the tournaments. Players - the number of different players that played this archetype.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      selectInput(inputId = "presenceGraph", 
                                  label = h4("Type of Graph"),
                                  choices = c("Pie Chart","Histogram")),
                      bsPopover(id = "presenceGraph", 
                                title = "Pie Chart or Histogram?",
                                content = "Select the type of graph you want to display: a pie chart or a histogram.", 
                                placement = "top", 
                                trigger = "hover"),
                    ),

                    mainPanel(
                      plotOutput("plotPresence")
                    )
           ),
           tabPanel("Win Rate",
                    sidebarPanel(
                      
                      selectInput(inputId = "winrateFormat", 
                                  label = h4("Format"),
                                  choices = c("Modern","Pioneer","Pauper")),
                      bsPopover(id = "winrateFormat", 
                                title = "Select the format of tournaments you want to cover.", 
                                content = "Currently only Modern and Pioneer are supported for archetype recognition",
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId="winrateDates1", 
                                label=h4("From"), 
                                value = as.Date(maxDate) - 27,
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "winrateDates1", 
                                title = "Beginning date",
                                content = "Select the first date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId="winrateDates2", 
                                label = h4("To"), 
                                value = maxDate + days(1),
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "winrateDates2", 
                                title = "End date",
                                content = "Select the last date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "winratePrelims", 
                                    label = h4("Preliminaries"), 
                                    value = TRUE),
                      bsPopover(id = "winratePrelims", 
                                title = "Preliminary data",
                                content = "Indicate whether you want to include or not Preliminary data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "winrateChallenges", 
                                    label = h4("Major Official Events"), 
                                    value = TRUE),
                      bsPopover(id = "winrateChallenges", 
                                title = "Major Event data",
                                content = "Indicate whether you want to include or not Challenge and bigger event data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      numericInput(inputId='winrateShare', 
                                   label = h4("Percent for \"Other\""),
                                   value = 2,
                                   min = 0.1,
                                   max = 10,
                                   step = 0.1),
                      bsPopover(id = "winrateShare", 
                                title = "Percentage to be added to \"Other\"",
                                content = "Select the percentage under which a deck is put in the \"Other\" category.",
                                placement = "top", 
                                trigger = "hover"),
                    ),
                    
                    mainPanel(
                      plotOutput("plotWinrate")
                    )
           ),
           tabPanel("Winrate vs Presence (full)",
                    sidebarPanel(
                      
                      selectInput(inputId = "wvpfFormat", 
                                  label = h4("Format"),
                                  choices = c("Modern","Pioneer","Pauper")),
                      bsPopover(id = "wvpfFormat", 
                                title = "Select the format of tournaments you want to cover.", 
                                content = "Currently only Modern and Pioneer are supported for archetype recognition",
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "wvpfDates1", 
                                label = h4("From"), 
                                value = as.Date(maxDate) - 27,
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "wvpfDates1", 
                                title = "Beginning date",
                                content = "Select the first date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "wvpfDates2", 
                                label = h4("To"), 
                                value = maxDate + days(1),
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "wvpfDates2", 
                                title = "End date",
                                content = "Select the last date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "wvpfPrelims", 
                                    label = h4("Preliminaries"), 
                                    value = TRUE),
                      bsPopover(id = "wvpfPrelims", 
                                title = "Preliminary data",
                                content = "Indicate whether you want to include or not Preliminary data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "wvpfChallenges", 
                                    label = h4("Major Official Events"), 
                                    value = TRUE),
                      bsPopover(id = "wvpfChallenges", 
                                title = "Major Event data",
                                content = "Indicate whether you want to include or not Challenge and bigger event data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      numericInput(inputId = "diam_ratio", 
                                   label = h4("Diameter ratio"),
                                   value = 0.3,
                                   min = 0.1,
                                   max = 10,
                                   step = 0.1),
                      bsPopover(id = "diam_ratio", 
                                title = "How large do you want the circles to be?", 
                                content = "Enter a number to increase or reduce the diameter of the circles.",
                                placement = "top", 
                                trigger = "hover"),
                      
                      selectInput(inputId = "diameters", 
                                  label = h4("Diameters based on"), 
                                  choices = c("Players", "Copies", "Matches")),
                      bsPopover(id = "diameters", 
                                title = "Select the variable that is used to determine the diameter of the circles.", 
                                content = "Matches - the overall number of matches of the archetype, played in Swiss rounds and top8 if applicable. Copies - the number of times the archetype appeared in the tournaments. Players - the number of different players that played this archetype.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      selectInput(inputId = "wvpfPresence", 
                                  label = h4("Type of Presence"), 
                                  choices = c("Matches", "Players", "Copies")),
                      bsPopover(id = "wvpfPresence", 
                                title = "Select the variable that is used to determine archetype presence.", 
                                content = "Matches - the overall number of matches of the archetype, played in Swiss rounds and top8 if applicable. Copies - the number of times the archetype appeared in the tournaments. Players - the number of different players that played this archetype.", 
                                placement = "top", 
                                trigger = "hover"),
                  
                      checkboxInput(inputId = "isLog", 
                                    label = h4("Logarithmic scale"), 
                                    value = TRUE),
                      bsPopover(id = "isLog", 
                                title = "Logarithm of the presence", 
                                content = "Should the presence be displayed with a logarithmic or linear scale?",
                                placement = "top", 
                                trigger = "hover")
                    ),
                    
                    mainPanel(
                      girafeOutput("plotWvpf", width = "90%", height = "90%")
                    )
           ),
           tabPanel("Winrate vs Presence (most present)",
                    sidebarPanel(
                      selectInput(inputId = "wvpmpFormat", 
                                  label = h4("Format"),
                                  choices = c("Modern","Pioneer","Pauper")),
                      bsPopover(id = "wvpmpFormat", 
                                title = "Select the format of tournaments you want to cover.", 
                                content = "Currently only Modern and Pioneer are supported for archetype recognition",
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "wvpmpDates1", 
                                label = h4("From"), 
                                value = as.Date(maxDate) - 27,
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "wvpmpDates1", 
                                title = "Beginning date",
                                content = "Select the first date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "wvpmpDates2", 
                                label = h4("To"), 
                                value = maxDate + days(1),
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "wvpmpDates2", 
                                title = "End date",
                                content = "Select the last date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "wvpmpPrelims", 
                                    label = h4("Preliminaries"), 
                                    value = TRUE),
                      bsPopover(id = "wvpmpPrelims", 
                                title = "Preliminary data",
                                content = "Indicate whether you want to include or not Preliminary data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "wvpmpChallenges", 
                                    label = h4("Major Official Events"), 
                                    value = TRUE),
                      bsPopover(id = "wvpmpChallenges", 
                                title = "Major Event data",
                                content = "Indicate whether you want to include or not Challenge and bigger event data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      numericInput(inputId = "wvpmpNoClusters", 
                                   label = h4("Number of clusters"),
                                   value = 4,
                                   min = 1,
                                   max = 50,
                                   step = 1),
                      bsPopover(id = "wvpmpNoClusters", 
                                title = "How many clusters do you want?", 
                                content = "Enter a number to select the number of clusters you want to see on the graph.",
                                placement = "top", 
                                trigger = "hover")
                    ),
                    
                    mainPanel(
                      girafeOutput("plotWvpmp", width = "90%", height = "90%")
                    )
           ),
           tabPanel("Tiers",
                    sidebarPanel(
                      selectInput(inputId = "lcFormat", 
                                  label = h4("Format"),
                                  choices = c("Modern","Pioneer","Pauper")),
                      bsPopover(id = "lcFormat", 
                                title = "Select the format of tournaments you want to cover.", 
                                content = "Currently only Modern and Pioneer are supported for archetype recognition",
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "lcDates1", 
                                label = h4("From"), 
                                value = as.Date(maxDate) - 27,
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "lcDates1", 
                                title = "Beginning date",
                                content = "Select the first date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "lcDates2", 
                                label = h4("To"), 
                                value = maxDate + days(1),
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "lcDates2", 
                                title = "End date",
                                content = "Select the last date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "lcPrelims", 
                                    label = h4("Preliminaries"), 
                                    value = TRUE),
                      bsPopover(id = "lcPrelims", 
                                title = "Preliminary data",
                                content = "Indicate whether you want to include or not Preliminary data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "lcChallenges", 
                                    label = h4("Major Official Events"), 
                                    value = TRUE),
                      bsPopover(id = "lcChallenges", 
                                title = "Major Event data",
                                content = "Indicate whether you want to include or not Challenge and bigger event data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      numericInput(inputId = "lcPresence_Weight", 
                                   label = h4("Weight of Presence"),
                                   value = 1,
                                   min = 0.1,
                                   max = 10,
                                   step = 0.1),
                      bsPopover(id = "lcPresence_Weight", 
                                title = "How impactful should the presence be in the calculation?",
                                content = "Enter the number that multiplies the value of the presence in the sum of presence and win rate to weigh it.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      numericInput(inputId = "lcPPR_Weight", 
                                   label = h4("Weight of Win Rate"),
                                   value = 1,
                                   min = 0.1,
                                   max = 10,
                                   step = 0.1),
                      bsPopover(id = "lcPPR_Weight", 
                                title = "How impactful should the win rate be in the calculation?",
                                content = "Enter the number that multiplies the value of the win rate in the sum of presence and win rate to weigh it.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      numericInput(inputId = "lcHistShare", 
                                   label = h4("Minimum presence to appear"),
                                   value = 2,
                                   min = 0.1,
                                   max = 10,
                                   step = 0.1),
                      bsPopover(id = "lcHistShare", 
                                title = "Presence percentage to make it on the graph",
                                content = "Enter the minimum presence percentage required for an archetype to appear on the graph.", 
                                placement = "top", 
                                trigger = "hover"),
                    ),
                    
                    mainPanel(
                      girafeOutput("plotLc", width = "90%", height = "90%")
                    )
           ),
           
           tabPanel("Archetype details",
                    sidebarPanel(
                      selectInput(inputId = "dtFormat", 
                                  label = h4("Format"),
                                  choices = c("Modern","Pioneer","Pauper")),
                      bsPopover(id = "dtFormat", 
                                title = "Select the format of tournaments you want to cover.", 
                                content = "Currently only Modern and Pionneer are supported for archetype recognition",
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "dtDates1", 
                                label = h4("From"), 
                                value = as.Date(maxDate) - 27,
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "dtDates1", 
                                title = "Beginning date",
                                content = "Select the first date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "dtDates2", 
                                label = h4("To"), 
                                value = maxDate + days(1),
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "dtDates2", 
                                title = "End date",
                                content = "Select the last date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "dtPrelims", 
                                    label = h4("Preliminaries"), 
                                    value = TRUE),
                      bsPopover(id = "dtPrelims", 
                                title = "Preliminary data",
                                content = "Indicate whether you want to include or not Preliminary data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "dtChallenges", 
                                    label = h4("Major Official Events"), 
                                    value = TRUE),
                      bsPopover(id = "dtChallenges", 
                                title = "Major Event data",
                                content = "Indicate whether you want to include or not Challenge and bigger event data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      downloadButton(outputId = "archetypeTableDL",
                                     label = "Download data")
                    ),
                    
                    mainPanel(
                      DT::dataTableOutput("archetypeTable")
                    )
           ),
           
           ######################################################
           # tabPanel("MD Cards",
           #          sidebarPanel(
           #            selectInput(inputId = "mdFormat", 
           #                        label = h4("Format"),
           #                        choices = c("Modern","Pioneer","Pauper")),
           #            bsPopover(id = "mdFormat", 
           #                      title = "Select the format of tournaments you want to cover.", 
           #                      content = "Currently only Modern and Pionneer are supported for archetype recognition",
           #                      placement = "top", 
           #                      trigger = "hover"),
           #            
           #            dateInput(inputId = "mdDates1", 
           #                      label = h4("From"), 
           #                      value = as.Date(maxDate) - 27,
           #                      min = minDate, 
           #                      max = maxDate + days(1),
           #                      format = "yyyy-mm-dd"),
           #            bsPopover(id = "mdDates1", 
           #                      title = "Beginning date",
           #                      content = "Select the first date of the period you want to cover.", 
           #                      placement = "top", 
           #                      trigger = "hover"),
           #            
           #            dateInput(inputId = "mdDates2", 
           #                      label = h4("To"), 
           #                      value = maxDate + days(1),
           #                      min = minDate, 
           #                      max = maxDate + days(1),
           #                      format = "yyyy-mm-dd"),
           #            bsPopover(id = "mdDates2", 
           #                      title = "End date",
           #                      content = "Select the last date of the period you want to cover.", 
           #                      placement = "top", 
           #                      trigger = "hover"),
           #            
           #            checkboxInput(inputId = "mdPrelims", 
           #                          label = h4("Preliminaries"), 
           #                          value = TRUE),
           #            bsPopover(id = "mdPrelims", 
           #                      title = "Preliminary data",
           #                      content = "Indicate whether you want to include or not Preliminary data.", 
           #                      placement = "top", 
           #                      trigger = "hover"),
           #            
           #            checkboxInput(inputId = "mdChallenges", 
           #                          label = h4("Major Official Events"), 
           #                          value = TRUE),
           #            bsPopover(id = "mdChallenges", 
           #                      title = "Major Event data",
           #                      content = "Indicate whether you want to include or not Challenge and bigger event data.", 
           #                      placement = "top", 
           #                      trigger = "hover"),
           #            
           #            downloadButton(outputId = "MDTableDL",
           #                           label = "Download data")
           #          ),
           #          
           #          mainPanel(
           #            DT::dataTableOutput("MDTable")
           #          )
           # ),
           # 
           # tabPanel("SB Cards",
           #          sidebarPanel(
           #            selectInput(inputId = "sbFormat", 
           #                        label = h4("Format"),
           #                        choices = c("Modern","Pioneer","Pauper")),
           #            bsPopover(id = "sbFormat", 
           #                      title = "Select the format of tournaments you want to cover.", 
           #                      content = "Currently only Modern and Pionneer are supported for archetype recognition",
           #                      placement = "top", 
           #                      trigger = "hover"),
           #            
           #            dateInput(inputId = "sbDates1", 
           #                      label = h4("From"), 
           #                      value = as.Date(maxDate) - 27,
           #                      min = minDate, 
           #                      max = maxDate + days(1),
           #                      format = "yyyy-mm-dd"),
           #            bsPopover(id = "sbDates1", 
           #                      title = "Beginning date",
           #                      content = "Select the first date of the period you want to cover.", 
           #                      placement = "top", 
           #                      trigger = "hover"),
           #            
           #            dateInput(inputId = "sbDates2", 
           #                      label = h4("To"), 
           #                      value = maxDate + days(1),
           #                      min = minDate, 
           #                      max = maxDate + days(1),
           #                      format = "yyyy-mm-dd"),
           #            bsPopover(id = "sbDates2", 
           #                      title = "End date",
           #                      content = "Select the last date of the period you want to cover.", 
           #                      placement = "top", 
           #                      trigger = "hover"),
           #            
           #            checkboxInput(inputId = "sbPrelims", 
           #                          label = h4("Preliminaries"), 
           #                          value = TRUE),
           #            bsPopover(id = "sbPrelims", 
           #                      title = "Preliminary data",
           #                      content = "Indicate whether you want to include or not Preliminary data.", 
           #                      placement = "top", 
           #                      trigger = "hover"),
           #            
           #            checkboxInput(inputId = "sbChallenges", 
           #                          label = h4("Major Official Events"), 
           #                          value = TRUE),
           #            bsPopover(id = "sbChallenges", 
           #                      title = "Major Event data",
           #                      content = "Indicate whether you want to include or not Challenge and bigger event data.", 
           #                      placement = "top", 
           #                      trigger = "hover"),
           #            
           #            downloadButton(outputId = "SBTableDL",
           #                           label = "Download data")
           #          ),
           #          
           #          mainPanel(
           #            DT::dataTableOutput("SBTable")
           #          )
           # ),
           ######################################################
           
           tabPanel("Deck Lists",
                    sidebarPanel(
                      selectInput(inputId = "dlFormat", 
                                  label = h4("Format"),
                                  choices = c("Modern","Pioneer","Pauper")),
                      bsPopover(id = "dlFormat", 
                                title = "Select the format of tournaments you want to cover.", 
                                content = "Currently only Modern and Pioneer are supported for archetype recognition",
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "dlDates1", 
                                label = h4("From"), 
                                value = as.Date(maxDate) - 27,
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "dlDates1", 
                                title = "Beginning date",
                                content = "Select the first date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "dlDates2", 
                                label = h4("To"), 
                                value = maxDate + days(1),
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "dlDates2", 
                                title = "End date",
                                content = "Select the last date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "dlPrelims", 
                                    label = h4("Preliminaries"), 
                                    value = TRUE),
                      bsPopover(id = "dlPrelims", 
                                title = "Preliminary data",
                                content = "Indicate whether you want to include or not Preliminary data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "dlChallenges", 
                                    label = h4("Major Official Events"), 
                                    value = TRUE),
                      bsPopover(id = "dlChallenges", 
                                title = "Major Event data",
                                content = "Indicate whether you want to include or not Challenge and bigger event data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      uiOutput("dlUiArchetypes"),
                      
                      checkboxInput(inputId = "dlOnlyBest", 
                                    label = h4("Best performing decklist only"), 
                                    value = FALSE),
                      bsPopover(id = "dlOnlyBest", 
                                title = "A single decklist",
                                content = "Only display the most recent decklist with the highest number of points.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      selectInput(inputId = "dlDisplay", 
                                  label = h4("Display"),
                                  choices = c("URL","Breakdown")),
                      bsPopover(id = "dlDisplay", 
                                title = "Display the URL of the decklists or a breakdown of their cards.", 
                                content = "The breakdown lists all the cards appearing in the archetype and their average count.",
                                placement = "top", 
                                trigger = "hover"),
                      
                      downloadButton(outputId = "dlTableDL",
                                     label = "Download data")
                    ),
                    
                    
                    mainPanel(
                      DT::dataTableOutput("decklistTable")
                    )
           ),
           
           tabPanel("MD Card Win Rate",
                    sidebarPanel(
                      selectInput(inputId = "wrcMDFormat", 
                                  label = h4("Format"),
                                  choices = c("Modern","Pioneer","Pauper")),
                      bsPopover(id = "wrcMDFormat", 
                                title = "Select the format of tournaments you want to cover.", 
                                content = "Currently only Modern and Pioneer are supported for archetype recognition",
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "wrcMDDates1", 
                                label = h4("From"), 
                                value = as.Date(maxDate) - 27,
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "wrcMDDates1", 
                                title = "Beginning date",
                                content = "Select the first date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "wrcMDDates2", 
                                label = h4("To"), 
                                value = maxDate + days(1),
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "wrcMDDates2", 
                                title = "End date",
                                content = "Select the last date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "wrcMDPrelims", 
                                    label = h4("Preliminaries"), 
                                    value = TRUE),
                      bsPopover(id = "wrcMDPrelims", 
                                title = "Preliminary data",
                                content = "Indicate whether you want to include or not Preliminary data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "wrcMDChallenges", 
                                    label = h4("Major Official Events"), 
                                    value = TRUE),
                      bsPopover(id = "wrcMDChallenges", 
                                title = "Major Event data",
                                content = "Indicate whether you want to include or not Challenge and bigger event data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      uiOutput("wrcMDUiArchetypes"),
                      
                      uiOutput("wrcMDUiCards")
                    ),
                    
                    mainPanel(
                      htmlOutput("winratecomparisonMDText"),
                      htmlOutput("wcMDPicture")
                    )
           ),
           
           
           tabPanel("SB Card Win Rate",
                    sidebarPanel(
                      selectInput(inputId = "wrcSBFormat", 
                                  label = h4("Format"),
                                  choices = c("Modern","Pioneer","Pauper")),
                      bsPopover(id = "wrcSBFormat", 
                                title = "Select the format of tournaments you want to cover.", 
                                content = "Currently only Modern and Pioneer are supported for archetype recognition",
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "wrcSBDates1", 
                                label = h4("From"), 
                                value = as.Date(maxDate) - 27,
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "wrcSBDates1", 
                                title = "Beginning date",
                                content = "Select the first date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "wrcSBDates2", 
                                label = h4("To"), 
                                value = maxDate + days(1),
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "wrcSBDates2", 
                                title = "End date",
                                content = "Select the last date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "wrcSBPrelims", 
                                    label = h4("Preliminaries"), 
                                    value = TRUE),
                      bsPopover(id = "wrcSBPrelims", 
                                title = "Preliminary data",
                                content = "Indicate whether you want to include or not Preliminary data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "wrcSBChallenges", 
                                    label = h4("Major Official Events"), 
                                    value = TRUE),
                      bsPopover(id = "wrcSBChallenges", 
                                title = "Major Event data",
                                content = "Indicate whether you want to include or not Challenge and bigger event data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      uiOutput("wrcSBUiArchetypes"),
                      
                      uiOutput("wrcSBUiCards")
                    ),
                    
                    mainPanel(
                      htmlOutput("winratecomparisonSBText"),
                      htmlOutput("wcSBPicture")
                    )
           ),
           
           tabPanel("Event sources (URL)",
                    sidebarPanel(
                      selectInput(inputId = "euFormat", 
                                  label = h4("Format"),
                                  choices = c("Modern","Pioneer","Pauper")),
                      bsPopover(id = "euFormat", 
                                title = "Select the format of tournaments you want to cover.", 
                                content = "Currently only Modern and Pioneer are supported for archetype recognition",
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "euDates1", 
                                label = h4("From"), 
                                value = as.Date(maxDate) - 27,
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "euDates1", 
                                title = "Beginning date",
                                content = "Select the first date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "euDates2", 
                                label = h4("To"), 
                                value = maxDate + days(1),
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "euDates2", 
                                title = "End date",
                                content = "Select the last date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "euPrelims", 
                                    label = h4("Preliminaries"), 
                                    value = TRUE),
                      bsPopover(id = "euPrelims", 
                                title = "Preliminary data",
                                content = "Indicate whether you want to include or not Preliminary data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "euChallenges", 
                                    label = h4("Major Official Events"), 
                                    value = TRUE),
                      bsPopover(id = "euChallenges", 
                                title = "Major Event data",
                                content = "Indicate whether you want to include or not Challenge and bigger event data.", 
                                placement = "top", 
                                trigger = "hover")
                    ),
                    
                    mainPanel(
                      DT::dataTableOutput("eventURL")
                    )
           ),
           
           tabPanel("Data description",
                    sidebarPanel(
                      selectInput(inputId = "eiFormat", 
                                  label = h4("Format"),
                                  choices = c("Modern","Pioneer","Pauper")),
                      bsPopover(id = "eiFormat", 
                                title = "Select the format of tournaments you want to cover.", 
                                content = "Currently only Modern and Pioneer are supported for archetype recognition",
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "eiDates1", 
                                label = h4("From"), 
                                value = as.Date(maxDate) - 27,
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "eiDates1", 
                                title = "Beginning date",
                                content = "Select the first date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      dateInput(inputId = "eiDates2", 
                                label = h4("To"), 
                                value = maxDate + days(1),
                                min = minDate, 
                                max = maxDate + days(1),
                                format = "yyyy-mm-dd"),
                      bsPopover(id = "eiDates2", 
                                title = "End date",
                                content = "Select the last date of the period you want to cover.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "eiPrelims", 
                                    label = h4("Preliminaries"), 
                                    value = TRUE),
                      bsPopover(id = "eiPrelims", 
                                title = "Preliminary data",
                                content = "Indicate whether you want to include or not Preliminary data.", 
                                placement = "top", 
                                trigger = "hover"),
                      
                      checkboxInput(inputId = "eiChallenges", 
                                    label = h4("Major Official Events"), 
                                    value = TRUE),
                      bsPopover(id = "eiChallenges", 
                                title = "Major Event data",
                                content = "Indicate whether you want to include or not Challenge and bigger event data.", 
                                placement = "top", 
                                trigger = "hover")
                    ),
                    
                    mainPanel(
                      verbatimTextOutput("eventInfo")
                    )
           ),
           
           tabPanel("Resources",
                    
                    mainPanel(
                      p("My thanks to ", a(href="https://twitter.com/filipebadaro",
                                           target="_blank",
                                           "Filipe Badaró (Phelps-san)"),
                        "for all the work to acquire the data.",
                        "\nYou can find his work on Github:",
                        a(href="https://github.com/Badaro/MTGODecklistCache",
                          target="_blank",
                          "\nthe scraper"), 
                        " to get the data from WotC's website \nand",
                        a(href="https://github.com/Badaro/MTGOArchetypeParser",
                          target="_blank",
                          "the parser"),
                        " to find archetypes based on decklists.",
                        "I would also like to thank ",
                        a(href="https://twitter.com/Pelvin_",
                          target="_blank",
                        "Pelvin"),
                          "and",
                        a(href="https://twitter.com/SoulsR4",
                          target="_blank",
                          "SoulsR"),
                          "from the",
                        a(href="https://discord.gg/F9U5qSq",
                          target="_blank",
                          "Modern Fr"),
                          "and",
                        a(href="https://discord.gg/2YBCZnA",
                          target="_blank",
                          "Pioneer Fr"),
                          "Discord servers
                        for their help with the data generation and the Pioneer archetype detection."
                        )
                    )
           )
)
